author: "@xlgmokha"
baseurl: ""
description: "You're looking at it."
domain: codechica.ca
lang: 'en'
markdown: kramdown
page_excerpts: true
title: CodeChica++
url: https://codechica.github.io
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "lessons"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "guides"
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-youtube
