name: Continuous Integration
on:
  - push
  - workflow_dispatch
jobs:
  lab-01-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: cd labs/01 && go test -v ./...
