name: Continuous Integration
on:
  - push
  - workflow_dispatch
jobs:
  lab-00-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: labs/00/package-lock.json
      - run: cd labs/00 && npm install && npm run test
  lab-01-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: cd labs/01 && go test -v ./...
